DROP DATABASE IF EXISTS prision_libertad;

CREATE DATABASE prision_libertad;

USE prision_libertad;

CREATE TABLE permisos(
	IDPERMISOS TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CREAR TINYINT(1) NOT NULL,
	EDITAR TINYINT(1) NOT NULL,
	BORRAR TINYINT(1) NOT NULL,
	MODERAR_COMENTARIOS TINYINT(1) NOT NULL,
	MODERAR_USUARIOS TINYINT(1) NOT NULL,
	MODERAR_VIDEOS TINYINT(1) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE usuarios(
	IDUSUARIOS INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE_USUARIO VARCHAR(20) NOT NULL UNIQUE,
	CONTRASENIA VARCHAR(32) NOT NULL,
	U_ESTADO BIT NOT NULL,
	FKPERMISOS TINYINT(2) UNSIGNED,

	FOREIGN KEY(FKPERMISOS) REFERENCES permisos(IDPERMISOS)
)ENGINE=InnoDB;

CREATE TABLE articulos(
	IDARTICULO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	AUTOR VARCHAR(50) NOT NULL,
	AÑO YEAR NOT NULL,
	DURACION TIME,
	FECHA_ALTA DATETIME,
	IMAGENES VARCHAR(50),
	IMG_DESTACADA VARCHAR(50),
	A_ESTADO BIT NOT NULL,
	FKUSUARIO INT UNSIGNED,

	FOREIGN KEY(FKUSUARIO) REFERENCES usuarios(IDUSUARIOS)
)ENGINE=InnoDB;

CREATE TABLE articulos_es(
	IDARTICULO_ES INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITULO_ES VARCHAR(50) NOT NULL,
	DESCRIPCION TEXT,
	VIDEO_ES VARCHAR(50),
	FKARTICULO INT UNSIGNED,
	
	FOREIGN KEY(FKARTICULO) REFERENCES articulos(IDARTICULO)
)ENGINE=InnoDB;

CREATE TABLE articulos_en(
	IDARTICULO_EN INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITULO_EN VARCHAR(50) NOT NULL,
	DESCRIPCION TEXT,
	VIDEO_EN VARCHAR(50),
	FKARTICULO INT UNSIGNED,
	
	FOREIGN KEY(FKARTICULO) REFERENCES articulos(IDARTICULO)
)ENGINE=InnoDB;

CREATE TABLE comentarios(
	IDCOMENTARIO INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	COMENTARIO TEXT NOT NULL,
	FECHA_COMENTARIO DATETIME,
	C_ESTADO BIT NOT NULL,
	FKUSUARIO INT UNSIGNED,
	FKARTICULO INT UNSIGNED,
	
	FOREIGN KEY(FKUSUARIO) REFERENCES usuarios(IDUSUARIOS),
	FOREIGN KEY(FKARTICULO) REFERENCES articulos(IDARTICULO)	
)ENGINE=InnoDB;